- name: Show files
  shell: cmd
  run: |
    echo CURRENT DIR:
    cd
    echo LIST:
    dir

- name: Build DLL (x86)
  shell: cmd
  run: |
    cl /LD /EHsc circular.cpp gdiplus.lib /link /MACHINE:X86
